[package]
name = "cozy-machine"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tensorfs-core = { git = "https://github.com/cozy-creator/tensorfs.git", tag = "v0.3.87" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
fs2 = "0.4"
libc = "0.2"
rusqlite = { version = "0.32", features = ["bundled"] }
nix = { version = "0.31.3", default-features = false, features = ["fs", "socket", "uio", "user"] }
