[build-system]
requires = ["uv_build>=0.12.7,<0.13"]
build-backend = "uv_build"

[project]
name = "cozy-machine-cpu-input"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["cozy-runtime>=0.18.99,<0.19", "msgspec>=0.19,<1"]

[project.entry-points."cozy.application"]
default = "cpu_input:app"

[tool.uv.build-backend]
module-name = "cpu_input"
module-root = ""
